language: swift
osx_image: xcode9

branches:
  only:
    - develop
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
    
xcode_project: Memory.xcodeproj
xcode_scheme: MemoryTests
script:
    - fastlane test
    
