language: swift
osx_image: xcode9

branches:
  only:
    - develop
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
    
xcode_project: Memory.xcodeproj
xcode_scheme: MemoryTests
script:
    - fastlane tryOuts

notifications: 
  email:
    recipients: 
      - adrian.rosales@wikilane.com
      - scott.otoole@wikilane.com
    on_success: never
    on_failure: always

